### ISSUE TITLE
Sublime Mod4 Bindings

### ISSUE THREAD

**Issue by justusmaier** [david0/neo2-llkh#2]
Meine lieblings IDEs haben leider alle Probleme mit dem Neo Layout:
Webstorm (IntelliJ) hat kürzlich gepatcht, aber die Kombination mit AltGr+Shift+e/s/d/f zum markieren funktionieren nicht.
Sublime erkennt AltGr gar nicht.

Ich würde gerne dieses Paket testen, gibt es irgendwo eine Anleitung?

**Comment by david0** [comment]
Hi, die Nutzung ist denkbar einfach:
Die neo-llkh.exe unter https://github.com/david0/neo2-llkh/releases downloaden und starten. IntelliJ nutze ich täglich mit diesem Treiber.

**Comment by justusmaier** [comment]
Mh, mein Arbeitgeber will die Entwicklung unter Windows nicht unterstützen, ich brauche eine Lösung für Ubuntu oder besser MacOS.

Habe zuhause neo Treiber und ahk installiert (und eigentlich keine Probleme), inwiefern lohnt sich der Umstieg auf deine exe?

**Comment by justusmaier** [comment]
Ich bin zufrieden mit der Standardlösung unter MacOS mit Karabiner.
Wenn Ubuntu nicht supportet wird kann hier geschlossen werden.
